Fantasy_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('console/', include('console.urls')),
    path('missions/', include('missions.urls')),
    path('news/', include('news.urls')),
    path('personnel/', include('personnel.urls')),
    path('profile/', include('user_profiles.urls')),
    path('resources/', include('resources.urls')),
    path('shopping-basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

news/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.news, name='news'),
    path('<int:news_id>/', views.news_details, name='news_details'),
    path('add-news/', views.add_news, name='add_news'),
    path('pending-articles/', views.pending_articles, name='pending_articles'),
    path('edit-news/<int:news_id>', views.edit_news, name='edit_news'),
    path('delete-news/<int:news_id>', views.delete_news, name='delete_news'),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from personnel.models import Personnel

# Create your models here.
# ---------- set up choices for integer fields ---
TYPES = ((1, 'General'), (2, 'Systems'), (3, 'Discoveries'))
PUBLISH = ((0, 'Hidden'), (1, 'Displayed'))
class News(models.Model):
    """Setting up my model to update news"""
    title = models.CharField(max_length=150, null=False, blank=False)
    news_type = models.IntegerField(choices=TYPES, default=1)
    news_img = models.ImageField(null=True, blank=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        default='Anonymous',
        related_name='articles'
    )
    approved_post = models.IntegerField(choices=PUBLISH, default=0)
    publish_date = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)
    news_content = models.TextField(
        max_length=4000,
        null=False,
        blank=False,
        default=''
    )
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        """set up our ordering for this model"""
        ordering = ['-publish_date']
        verbose_name_plural = "News"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """setting up the method for generating slug"""
        if not self.slug:
            self.slug = slugify(f'{self.news_type}-{self.title}')
        return super().save(*args, **kwargs)

news/forms.py
from django import forms
from django.forms import Select

from .models import News
from missions.widgets import CustomClearableFileInput

TYPES = ((1, 'General'), (2, 'Systems'), (3, 'Discoveries'))

class NewsForm(forms.ModelForm):
    """Set up the news form for new content"""
    class Meta:
        """set up for our widgets"""
        model = News
        fields = [
            'title',
            'news_type',
            'news_img',
            'news_content',
            'approved_post',
        ]
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'Article Title Here'
                }
            ),
            'news_type': forms.RadioSelect(),
            'news_content': forms.Textarea(
                attrs={
                    'placeholder': 'Add title Content Here'
                }
            ),
            'approved_post': forms.Select(
                attrs={
                    'style': 'width: 200px;',
                }
            )
        }

    news_img = forms.ImageField(
        label='Image Upload',
        required=False,
        widget=CustomClearableFileInput,
    )


class ApproveNewsForm(forms.ModelForm):
    """set up our approval form for news articles"""
    def __init__(self, *args, **kwargs):
        super(ApproveNewsForm, self).__init__(*args, **kwargs)
        self.fields['approved_post'].label = 'How would you like to display this article?'
    class Meta:
        """Add form elements"""
        model = News
        fields = [
            'approved_post'
        ]
        widgets = {
            'approved_post': forms.Select(
                attrs={
                    'style': 'width: 100%;',
                }
            )
        }

news/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import News
from .forms import NewsForm, ApproveNewsForm

# Create your views here.


def news(request):
    """set up your news updates view"""
    articles = News.objects.filter(approved_post=1)
    context = {
        'articles': articles,
    }
    return render(request, 'news/news.html', context)


@login_required
def pending_articles(request):
    """Set up our template for unapproved articles"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    articles = News.objects.filter(approved_post=0)

    context = {
        'articles': articles,
        'from_homepage': True,
    }
    return render(request, 'news/news.html', context)


def news_details(request, news_id):
    """set up our drill down into specific news entry"""
    from_pending = False

    event = get_object_or_404(News, pk=news_id)

    if event.approved_post == 0:
        from_pending = True

    if request.method == 'POST':
        form = ApproveNewsForm(
            request.POST,
            instance=event
        )
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'You have successfully changed the approval of the article!'
            )
            if event.approved_post == 0:
                from_pending = True
            else:
                from_pending = False
        else:
            messages.error(
                request,
                "You have failed to update this article's approval"
            )
    else:
        form = ApproveNewsForm(instance=event)

    context = {
        'event': event,
        'from_pending': from_pending,
        'form': form,
    }

    return render(request, 'news/news-details.html', context)


@login_required
def add_news(request):
    """set up our new view for adding a new article"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access thie Resource!'
        )
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = NewsForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            messages.success(
                request,
                'New Article is awaiting your review!'
            )
            return redirect(reverse('pending_articles'))
        else:
            messages.error(
                request,
                'Something went wrong - Please check through the form again!'
            )
    else:
        form = NewsForm()

    context = {
        'form': form,
    }
    return render(request, 'news/add-news.html', context)


@login_required
def edit_news(request, news_id):
    """set up how we activate editing news articles"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('news'))

    article = get_object_or_404(News, pk=news_id)
    if request.method == 'POST':
        form = NewsForm(
            request.POST,
            request.FILES,
            instance=article
        )
        if form.is_valid():
            form.save()
            messages.success(
                request,
                f'Successfully updated { article.title }'
            )
            return redirect(reverse('news'))
        else:
            messages.warning(
                request, (
                    'Failed to update Mission'
                    'Please check through the form again!'
                )
            )
    else:
        form = NewsForm(instance=article)
        messages.info(
            request,
            f'You are editing { article.title }'
        )

    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'news/edit-news.html', context)

@login_required
def delete_news(request, news_id):
    """set up delete news view"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    article = get_object_or_404(News, pk=news_id)

    if request.method == 'POST':
        article.delete()
        messages.success(
            request,
            f'You have successfully deleted { article.title }'
        )
        return(redirect(reverse('news')))

    context = {
        'article': article,
    }

    return render(request, 'news/delete-news.html', context)

news/templates/news/add-news.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Add an Article{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center">
        <h3 class="renegade page-heading">Add a New Article</h3>
        <p class="league page-subhead">
            Please use the form below to Add a News Article to the Operation
        </p>
    </div>
    <div class="col-12 content-titles text-center">
        <a href="{% url 'home' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Home</a>
        <a href="{% url 'console_add_entry' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Add Page</a>
        <a href="{% url 'console' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Console</a>
    </div>
  </div>
</div>
<hr class="menus">
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3 form-inner-content">
      <form action="{% url 'add_news' %}" method="POST" class="form mb-5 league card-origins" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          {% if field.name != 'news_img' %}
            <div class="my-4">
              {{ field | as_crispy_field }}
            </div>
          {% else %}
            {{ field }}
          {% endif %}
        {% endfor %}
        <div class="my-3 text-right">
          <a href="{% url 'console_add_entry' %}" class="btn-console-link"><i class="fas fa-chevron-circle-left"></i> Cancel</a>
          <button class="btn-console-link" type="submit">+ Add Article</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`You have chosen - ${file.name} - as your new image!`);
        });
    </script>
{% endblock %}

news/templates/news/delete-news.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Delete Article{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container">
    <div class="row text-center">
        <div class="col-12 text-center">
            <h3 class="renegade page-heading">Delete News Article</h3>
            <p class="league page-subhead">
                Are you sure you want to delete the following News Article?
            </p>
        </div>
        <hr class="menus">
        <div class="col-12">
            <p class="league page-subhead">{{ article.title|upper }} - {{ article.author }}</p>
            <p class="league page-subhead">Published on {{ article.publish_date }}</p>
        </div>
        <div class="col-12 menus page-heading my-5">
            <h1>WARNING - Deleting this article will remove it from the console permanently!</h1>
        </div>
        <div class="my-3">
            <form method="post" class="form">
                {% csrf_token %}
                <a href="{% url 'news' %}" class="btn-lg btn-console-link"><i class="fas fa-chevron-circle-left"></i> Cancel</a>
                <button class="btn-lg btn-console-link" type="submit">X Delete</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

news/templates/news/edit-news.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Edit an Article{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center">
        <h3 class="renegade page-heading">Edit a News Article</h3>
        <p class="league page-subhead">
            Please use the form below to Edit a News Article for the Operation
        </p>
    </div>
    <div class="col-12 content-titles text-center">
        <a href="{% url 'home' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Home</a>
        <a href="{% url 'news' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Articles</a>
        <a href="{% url 'console' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Console</a>
    </div>
  </div>
</div>
<hr class="menus">
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3 form-inner-content">
      <form action="{% url 'edit_news' article.id %}" method="POST" class="form mb-5 league card-origins" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          {% if field.name != 'news_img' %}
            <div class="my-4">
              {{ field | as_crispy_field }}
            </div>
          {% else %}
            {{ field }}
          {% endif %}
        {% endfor %}
        <div class="my-3 text-right">
          <a href="{% url 'news' %}" class="btn-console-link"><i class="fas fa-chevron-circle-left"></i> Cancel</a>
          <button class="btn-console-link" type="submit">+ Edit Article</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`You have chosen - ${file.name} - as your new image!`);
        });
    </script>
{% endblock %}

news/templates/news/new-details.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - News Updates{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
{% endblock %}

news/templates/news/news-details.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- add extra css stylesheet -->
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/news-details.css' %}">
{% endblock %}

<!-- set up tab extra title -->
{% block extra_title %} - News Report{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container text-center current-news">
    <div class="row">
        <div class="col-12 text-center">
            <h3 class="renegade page-heading">News Report</h3>
            <p class="league page-subhead">
                This is the news article you have selected
            </p>
        </div>
        <div class="col-12 content-titles mb-5">
            {% if from_pending == True %}
            <a href="{% url 'pending_articles' %}" class="menus">
                <i class="fas fa-chevron-circle-left"></i> Pending Articles 
            </a>
            {% else %}
            <a href="{% url 'news' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> News Articles</a>
            {% endif %}
            <a href="{% url 'console' %}" class="menus btn">
                <i class="fas fa-chevron-circle-left"></i> Console 
            </a>
        </div>
    </div>
</div>
<hr class="menus">
<!-- main content for displaying news articles -->
<div class="container league current-news">
    <div class="row">
        {% if request.user.is_superuser %}
        <div class="col-12 text-center mb-5">
            <a href="{% url 'edit_news' event.id %}" class="btn-console-link">
                <span class="my-3">Edit Article</span>
            </a>
            <a href="{% url 'delete_news' event.id %}" class="btn-console-link">
                <span class="my-3">Delete Article</span>
            </a>
        </div>
        {% endif %}
        <div class="col-12 text-center mb-3">
            {% if event.news_type == 1 %}
            <img src="{{ MEDIA_URL }}announcement-default-img.png"
                alt="General announcement default image" class="image-top">
            {% elif event.news_type == 2 %}
            <img src="{{ MEDIA_URL }}system-default-img.png" alt="System dault image"
                class="image-top">
            {% else %} {% if event.news_img %}
            <img src="{{ n.news_img.url }}" alt="{{ n.title }} image" class="image-top">
            {% else %}
            <img src="{{ MEDIA_URL }}discover-default-img.png"
                alt="General announcement deault image" class="image-top">
            {% endif %} {% endif %}
        </div>
        <div class="col-12">
            <h1 class="league mb-3 mx-4 text-center"><strong>{{ event.title }}</strong></h1>
        </div>
        <div class="col-12 mb-5 text-center">
            <h5>Published on <strong><em>{{ event.publish_date }}</em></strong>
                    Article by <strong><em>{{ event.author }}</em></strong></h5>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-12 col-md-6 offset-md-3 news-content">
            {{ event.news_content|linebreaks }}
        </div>
    </div>
</div>
{% if request.user.is_superuser %}
<hr class="menus">
<div class="container text-center league">
    <div class="row">
        <div class="col-12">
            <p class="page-subhead">This article is currently {{ event.get_approved_post_display|lower }} to the general users.</p>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-8 offset-2 col-md-4 offset-md-4 form-inner-content">
            <form action="{% url 'news_details' event.id %}" method="POST" class="form mb-5 card-origins approval-form">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn-console-link my-3" type="submit">Update Approval</button>
            </form>
        </div>
    </div>
</div>
{% endif %}
<!-- back to top button -->
<div class="container">
    <div class="row">
        <div class="col-12 text-center btt-btn">
            <a class="btt-link btn">
                <i class="fas fa-arrow-up"></i> Back to Top
                <i class="fas fa-arrow-up"></i>
            </a>
        </div>
    </div>
</div>
{% endblock content %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %} {{ block.super }}
<script>
    $(".btt-link").click(function () {
        window.scrollTo(0, 0);
    });
</script>
{% endblock %}

news/templates/news/news.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - News Updates{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container text-center">
  <div class="row">
    <div class="col-12 text-center">
      <h3 class="renegade page-heading">News updates</h3>
      <p class="league page-subhead">
        {% if from_homepage %}
        These are the Unapproved News articles awaiting your review
        {% else %}
        Here are all the news updates posted to the message board;
      </p>
      <p class="league page-subhead">
        from system updates, discoveries and general announcements.
        {% endif %}
      </p>
    </div>
    <div class="col-12 content-titles">
      {% if from_homepage %}
      <a href="{% url 'home' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Home</a>
      {% endif %}
      <a href="{% url 'console' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Console</a>
    </div>
  </div>
</div>
<hr class="menus">
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center content-titles">
      {% if from_homepage and request.user.is_superuser %}
      <a href="{% url 'news' %}" class="void"><i class="fas fa-chevron-circle-left"></i> Approved Articles</a>
      {% elif request.user.is_superuser %}
      <a href="{% url 'pending_articles' %}" class="void"><i class="fas fa-chevron-circle-left"></i> Pending Articles</a>
      {% endif %}
    </div>
  </div>
  <div class="row mb-5">
  {% if articles|length == 0 %}
    <div class="col-12 text-center league my-3">
      <h5>There are no news articles to display!</h5>
    </div>
  {% endif %}
  </div>
  <div class="row mb-5">
    {% for a in articles %}
    <div class="col-sm-6 col-md-4 col-xl-3 mb-1">
      <div class="card news-card">
        <div class="row">
          <div class="col">
            <div class="card-img-holder">
              <a href="{% url 'news_details' a.id %}">
                {% if a.news_type == 1 %}
                <img
                  src="{{ MEDIA_URL }}announcement-default-img.png"
                  alt="system issue default image"
                  class="card-img-top">
                {% elif a.news_type == 2 %}
                <img
                  src="{{ MEDIA_URL }}system-default-img.png"
                  alt="Discoveries dault image"
                  class="card-img-top">
                {% else %} {% if a.news_img %}
                <img
                  src="{{ a.news_img.url }}"
                  alt="{{ a.title }} image"
                  class="card-img-top">
                {% else %}
                <img
                  src="{{ MEDIA_URL }}discover-default-img.png"
                  alt="General announcement deault image"
                  class="card-img-top">
                {% endif %} {% endif %}
              </a>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <a href="{% url 'news_details' a.id %}">
              <div class="card-body text-center void">
                <h5 class="card-title">{{ a.title }}</h5>
                <p class="card-origins"><em>by {{ a.author }}</em></p>
              </div>
            </a>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <a href="{% url 'news_details' a.id %}" class="btn btn-view"
              ><span class="d-none d-lg-inline-block">View </span>
              <i class="fas fa-eye"></i
            ></a>
            {% if request.user.is_superuser %}
            <a href="{% url 'edit_news' a.id %}" class="btn btn-edit"><i class="fas fa-edit"></i></a>
            <a href="{% url 'delete_news' a.id %}" class="btn btn-delete"
              ><i class="fas fa-trash-alt"></i
            ></a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:1 %}
    <div class="col-12 d-sm-none">
      <hr class="menus my-3">
    </div>
    {% endif %} {% if forloop.counter|divisibleby:2 %}
    <div class="col-12 d-none d-sm-block d-md-none">
      <hr class="menus my-3">
    </div>
    {% endif %} {% if forloop.counter|divisibleby:3 %}
    <div class="col-12 d-none d-md-block d-xl-none">
      <hr class="menus my-3">
    </div>
    {% endif %} {% if forloop.counter|divisibleby:4 %}
    <div class="col-12 d-none d-xl-block">
      <hr class="menus my-3">
    </div>
    {% endif %} {% endfor %}
  </div>
</div>
<div class="container my-5">
  <div class="row">
    <div class="col-12 text-center btt-btn">
      <a class="btt-link btn">
        <i class="fas fa-arrow-up"></i> Back to Top
        <i class="fas fa-arrow-up"></i>
      </a>
    </div>
  </div>
</div>
{% endblock content %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %} {{ block.super }}
<script>
  $(".btt-link").click(function () {
    window.scrollTo(0, 0);
  });
</script>
{% endblock %}