Fantasy_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('console/', include('console.urls')),
    path('missions/', include('missions.urls')),
    path('news/', include('news.urls')),
    path('personnel/', include('personnel.urls')),
    path('profile/', include('user_profiles.urls')),
    path('resources/', include('resources.urls')),
    path('shopping-basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

personnel/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.personnel, name='personnel'),
    path(
        '<int:personnel_id>/',
        views.personnel_details,
        name='personnel_details'
    ),
    path(
        'add-member/',
        views.add_member,
        name='add_member'
    ),
    path('pending-members/', views.pending_members, name='pending_members'),
    path('edit-member/<int:personnel_id>', views.edit_member, name='edit_member'),
    path('delete-member/<int:personnel_id>', views.delete_member, name='delete_member'),
]

personnel/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string


def unique_member_id():
    random_id = int(get_random_string(10, allowed_chars='0123456789'))
    return random_id

RANK = ((1, "Rookie"), (2, "Soldier"), (3, "Veteran"), (4, "Commander"),)
STATUSES = ((1, "Active"), (2, "Leave"), (3, "Medical Leave"), (4, "Retired"), (5, "Deceased"))
DISPLAY = ((0, 'Hidden'), (1, 'Shown'))
# Create your models here.
class Personnel(models.Model):
    """Set up model for our team members"""
    name = models.CharField(max_length=100, null=False, blank=False, unique=True)
    age = models.PositiveIntegerField(default=0)
    originated_from = models.CharField(max_length=100, null=False, blank=False)
    rank = models.PositiveIntegerField(choices=RANK, default=1)
    speciality = models.TextField(default="", max_length=1000)
    current_status = models.PositiveIntegerField(choices=STATUSES, default=1)
    joined = models.DateField(auto_now_add=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True)
    authorised = models.PositiveIntegerField(choices=DISPLAY, default=0)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        """set up how the personnel is ordered"""
        ordering = ['-joined']
        verbose_name_plural = "Personnel"

    def __str__(self):
        """set up how we display choices"""
        return self.name

    def save(self, *args, **kwargs):
        """setting up the method for generating slug"""
        if not self.slug:
            self.slug = slugify(f'{self.name}-{self.originated_from}-{self.age}')
        return super().save(*args, **kwargs)

personnel/forms.py
from django import forms
from django.forms import Select

from .models import Personnel
from missions.widgets import CustomClearableFileInput


class PersonnelForm(forms.ModelForm):
    """set up our personnel form to add new members"""
    class Meta:
        """set up our personnel form"""
        model = Personnel
        fields = [
            'name',
            'age',
            'originated_from',
            'rank',
            'speciality',
            'current_status',
            'profile_image',
            'image_url',
            'authorised',
        ]
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Full Name Here',
                }
            ),
            'age': forms.NumberInput(
                attrs={
                    'style': 'width: 100px;',
                }
            ),
            'originated_from': forms.TextInput(
                attrs={
                    'placeholder': 'Please Enter Hometown Area'
                }
            ),
            'rank': forms.Select(
                attrs={
                    'style': 'width: 200px;',
                }
            ),
            'speciality': forms.Textarea(
                attrs={
                    'placeholder': 'Enter Charcter Info Here',
                }
            ),
            'current_status': forms.Select(
                attrs={
                    'style': 'width: 200px;',
                }
            ),
            'image_url': forms.TextInput(
                attrs={
                    'placeholder': 'Online Image URL'
                }
            ),
            'authorised': forms.Select(
                attrs={
                    'style': 'width: 200px;',
                }
            )
        }

    profile_image = forms.ImageField(
        label='Image',
        required=False,
        widget=CustomClearableFileInput
    )

class ApprovePersonnelForm(forms.ModelForm):
    """set up our personnel approval form"""
    def __init__(self, *args, **kwargs):
        super(ApprovePersonnelForm, self).__init__(*args, **kwargs)
        self.fields['authorised'].label = 'How would you like to display this member?'
    class Meta:
        """specific form details"""
        model = Personnel
        fields = [
            'authorised'
        ]
        widgets = {
            'authorised': forms.Select(
                attrs={
                    'style': 'width: 100%',
                }
            )
        }

personnel/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Personnel
from .forms import PersonnelForm, ApprovePersonnelForm

# Create your views here.


def personnel(request):
    """set up new page for displaying all content"""
    crew = Personnel.objects.filter(authorised=1)

    context = {
        'crew': crew,
    }

    return render(request, 'personnel/personnel.html', context)


@login_required
def pending_members(request):
    """set up our pending members authorisation page"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    crew = Personnel.objects.filter(authorised=0)

    context = {
        'crew': crew,
        'from_homepage': True,
    }

    return render(request, 'personnel/personnel.html', context)


def personnel_details(request, personnel_id):
    """create view to bring up the personnel specifics"""
    from_pending = False
    member = get_object_or_404(Personnel, pk=personnel_id)

    if member.authorised == 0:
        from_pending = True

    if request.method == 'POST':
        form = ApprovePersonnelForm(
            request.POST,
            instance=member
        )
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'You have successfully changed the approval of the member!'
            )
            if member.authorised == 0:
                from_pending = True
            else:
                from_pending = False
        else:
            messages.error(
                request,
                "You have failed to update this member's approval"
            )
    else:
        form = ApprovePersonnelForm(
            instance=member
        )

    context = {
        'member': member,
        'from_pending': from_pending,
        'form': form,
    }

    return render(request, 'personnel/personnel-details.html', context)


@login_required
def add_member(request):
    """ add new view for adding a member"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = PersonnelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'A New Member is awaiting review!'
            )
            return redirect(reverse('pending_members'))
        else:
            messages.error(
                request,
                'Something went wrong - Please check through the form again!'
            )
    else:
        form = PersonnelForm()

    context = {
        'form': form,
    }
    return render(request, 'personnel/add-member.html', context)


@login_required
def edit_member(request, personnel_id):
    """set up our view for editing members"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('personnel'))

    member = get_object_or_404(Personnel, pk=personnel_id)
    if request.method == 'POST':
        form = PersonnelForm(
            request.POST,
            request.FILES,
            instance=member
        )
        if form.is_valid():
            form.save()
            messages.success(
                request,
                f'Successfully updated { member.name }'
            )
            return redirect(reverse('personnel'))
        else:
            messages.error(
                request, (
                'Failed to update Mission'
                'Please check through the form again!')
            )
    else:
        form = PersonnelForm(instance=member)
        messages.info(
            request,
            f'You are editing { member.name }'
        )

    context = {
        'member': member,
        'form': form,
    }
    return render(request, 'personnel/edit-member.html', context)

@login_required
def delete_member(request, personnel_id):
    """
    set up the view to delete our members 
    if we no longer require them
    """
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    member = get_object_or_404(Personnel, pk=personnel_id)

    if request.method == 'POST':
        member.delete()
        messages.success(
            request,
            f'You have successfully deleted { member.name }'
        )
        return redirect(reverse('personnel'))

    context = {
        'member': member,
    }

    return render(request, 'personnel/delete-member.html', context)

personnel/templates/personnel/add-member.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Add Member{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center">
        <h3 class="renegade page-heading">Add a New Member</h3>
        <p class="league page-subhead">
            Please use the form below to Add a Member to the Operation</em>
        </p>
    </div>
    <div class="col-12 content-titles text-center">
        <a href="{% url 'home' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Home</a>
        <a href="{% url 'console_add_entry' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Add Page</a>
        <a href="{% url 'console' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Console</a>
    </div>
  </div>
</div>
<hr class="menus">
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3 form-inner-content">
      <form action="{% url 'add_member' %}" method="POST" class="form mb-5 league card-origins" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          {% if field.name != 'profile_image' %}
            <div class="my-4">
              {{ field | as_crispy_field }}
            </div>
          {% else %}
            {{ field }}
          {% endif %}
        {% endfor %}
        <div class="my-3 text-right">
          <a href="{% url 'console_add_entry' %}" class="btn-console-link"><i class="fas fa-chevron-circle-left"></i> Cancel</a>
          <button class="btn-console-link" type="submit">+ Add Member</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`You have chosen - ${file.name} - as your new image!`);
        });
    </script>
{% endblock %}

personnel/templates/personnel/delete-member.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Delete Member{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container">
    <div class="row text-center">
        <div class="col-12 text-center">
            <h3 class="renegade page-heading">Delete Member</h3>
            <p class="league page-subhead">
                Are you sure you want to delete the following Member of the League?</em>
            </p>
        </div>
        <hr class="menus">
        <div class="col-12">
            <p class="league page-subhead">{{ member.name|upper }} - {{ member.originated_from }}</p>
            <p class="league page-subhead">{{ member.get_rank_display }} - {{ member.get_current_status_display }}</p>
        </div>
        <div class="col-12 menus page-heading my-5">
            <h1>WARNING - Deleting this member will remove them from the roster permanently!</h1>
        </div>
        <div class="my-3">
            <form method="post" class="form">
                {% csrf_token %}
                <a href="{% url 'personnel' %}" class="btn-lg btn-console-link"><i class="fas fa-chevron-circle-left"></i> Cancel</a>
                <button class="btn-lg btn-console-link" type="submit">X Delete</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

personnel/templates/personnel/edit-member.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Edit Member{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center">
        <h3 class="renegade page-heading">Edit a Member</h3>
        <p class="league page-subhead">
            Please use the form below to Edit a Member of the Operation</em>
        </p>
    </div>
    <div class="col-12 content-titles text-center">
        <a href="{% url 'home' %}" class="menus"><i class="fas fa-chevron-circle-left"></i> Home</a>
        <a href="{% url 'personnel' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Add Page</a>
        <a href="{% url 'console' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Console</a>
    </div>
  </div>
</div>
<hr class="menus">
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3 form-inner-content">
      <form action="{% url 'edit_member' member.id %}" method="POST" class="form mb-5 league card-origins" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          {% if field.name != 'profile_image' %}
            <div class="my-4">
              {{ field | as_crispy_field }}
            </div>
          {% else %}
            {{ field }}
          {% endif %}
        {% endfor %}
        <div class="my-3 text-right">
          <a href="{% url 'personnel' %}" class="btn-console-link"><i class="fas fa-chevron-circle-left"></i> Cancel</a>
          <button class="btn-console-link" type="submit">+ Edit Member</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`You have chosen - ${file.name} - as your new image!`);
        });
    </script>
{% endblock %}

personnel/templates/personnel/personnel-details.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- add extra css stylesheet -->
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/personnel-details.css' %}" />
{% endblock %}

<!-- set up tab extra title -->
{% block extra_title %} - Personnel Details{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container text-center">
    <div class="row">
        <div class="col-12 text-center">
            <h3 class="renegade page-heading">Personnel Change</h3>
            <p class="league page-subhead">
                This is updated information regarding the member of personnel in question</em>
            </p>
        </div>
        <div class="col-12 content-titles menus">
            {% if from_pending == True %}
            <a href="{% url 'pending_members' %}" class="menus">
                <i class="fas fa-chevron-circle-left"></i> Pending Members 
            </a>
            {% else %}
            <a href="{% url 'personnel' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Personnel</a>
            {% endif %} 
            <a href="{% url 'console' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Console</a>
        </div>
    </div>
</div>
<hr class="menus" />
<div class="container current-personnel league">
    {% if request.user.is_superuser %}
    <div class="row mb-5">
        <div class="col-12 text-center">
            <a href="{% url 'edit_member' member.id %}" class="btn-console-link">
                <span class="my-3">Edit Member</span>
            </a>
            <a href="{% url 'delete_member' member.id %}" class="btn-console-link">
                <span class="my-3">Delete Member</span>
            </a>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-12 text-center">
            <h1 class=""><strong>{{ member.name }}</strong></h1>
        </div>
        <div class="col-12 text-center">
            <h3>{{ member.get_rank_display|upper }} - <em>{{ member.get_current_status_display }}</em></h3>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-12 col-lg-6 text-center mb-5">
            {% if member.profile_image %}
                <img class="profile-img" src="{{ member.profile_image.url }}" alt="{{ member.name }} profile image" />
            {% else %}
                <img class="profile-img" src="{{ MEDIA_URL }}no-image.png" alt="No image available" />
            {% endif %}
        </div>
        <div class="col-12 col-lg-6 personnel-desc">
            <p>Originating from {{ member.originated_from }}. </p>
            <br>
            <p>Their age is {{ member.age }} years old.</p>
            <br>
            <p>They joined the league on {{ member.joined }}.</p>
            <br>
            <p>{{ member.speciality|linebreaks }}</p>
            <br>
            <h4>Mission Leader for the following mission:</h4>
            {% if member.missions.all|length == 0 %}
            <p>They have currently lead no missions to this date.</p>
            {% endif %}
            <ul>
                {% for missions in member.missions.all %}
                    <li><a href="{% url 'mission_details' missions.id %}" class="plain-link menus">{{ missions }}</a></li> 
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% if request.user.is_superuser %}
<hr class="menus">
<div class="container text-center league">
    <div class="row">
        <div class="col-12">
            <p class="page-subhead">This roster is currently {{ member.get_authorised_display|lower }} to the general users.</p>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-8 offset-2 col-md-4 offset-md-4 form-inner-content">
            <form action="{% url 'personnel_details' member.id %}" method="POST" class="form mb-5 card-origins approval-form">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn-console-link my-3" type="submit">Update Approval</button>
            </form>
        </div>
    </div>
</div>
{% endif %}
<!-- back to top button -->
<div class="container">
    <div class="row">
        <div class="col-12 text-center btt-btn">
            <a class="btt-link btn">
                <i class="fas fa-arrow-up"></i> Back to Top
                <i class="fas fa-arrow-up"></i>
            </a>
        </div>
    </div>
</div>
<!-- footer elements -->
<div class="container footer-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
<footer class="d-none d-lg-block fixed-bottom text-center">
    <p class="my-2">
        This is a fan made, non profit site. Source materials and locations are
        described in README for project
    </p>
</footer>
{% endblock content %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}
<!-- page specific javascript -->
{% block postloadjs %} {{ block.super }}
<script>
    $(".btt-link").click(function () {
        window.scrollTo(0, 0);
    });
</script>
{% endblock %}

personnel/templates/personnel/personnel.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Personnel Roster{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container text-center">
  <div class="row">
    <div class="col-12 text-center">
      <h3 class="renegade page-heading">Personnel Roster</h3>
      <p class="league page-subhead">
        {% if from_homepage %} These are the Unauthorsied recruits awaiting your
        review {% else %} This is the current collection of team members that
        belong to the league. {% endif %}
      </p>
    </div>
    <div class="col-12 content-titles">
      {% if from_homepage %}
      <a href="{% url 'home' %}" class="menus"><i class="fas fa-chevron-circle-left"></i> Home</a>
      {% endif %}
      <a href="{% url 'console' %}" class="menus"><i class="fas fa-chevron-circle-left"></i> Console</a>
    </div>
  </div>
</div>
<hr class="menus" />
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center content-titles">
      {% if from_homepage and request.user.is_superuser %}
      <a href="{% url 'personnel' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Authorised Members</a>
      {% elif request.user.is_superuser %}
      <a href="{% url 'pending_members' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Pending Recruits</a>
      {% endif %}
    </div>
  </div>
  <div class="row my-5">
    {% if crew|length == 0 %}
    <div class="col-12 text-center league">
      <h5>There are no recruits to display!</h5>
    </div>
    {% endif %}
  </div>
  <div class="row mb-3">
    {% for c in crew %}
    <div class="col-10 offset-1 offset-sm-0 col-sm-6 col-md-4 col-xl-3 mb-1">
      <div class="card personnel-card">
        <a href="{% url 'personnel_details' c.id %}">
          <div class="row">
            <div class="col">
              <div class="card-img-holder">
                {% if c.profile_image %}
                <img
                  class="card-img-top"
                  src="{{ c.profile_image.url }}"
                  alt="{{ c.name }} profile image"
                />
                {% else %}
                <img
                  class="card-img-top"
                  src="{{ MEDIA_URL }}no-image.png"
                  alt="No image available"
                />
                {% endif %}
              </div>
            </div>
          </div>
          <div class="row void">
            <div class="col">
              <div class="card-body text-center">
                <h5 class="card-title">{{ c.name|upper }}</h5>
                <p class="card-origins">
                  from <em>{{ c.originated_from|lower }}</em>
                </p>
                <p class="card-text">
                  {{ c.get_rank_display }} -
                  <em>{{ c.get_current_status_display }}</em>
                </p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <a href="{% url 'personnel_details' c.id %}" class="btn btn-view"
                ><span class="d-none d-lg-inline-block">View </span>
                <i class="fas fa-eye"></i
              ></a>
              {% if request.user.is_superuser %}
              <a href="{% url 'edit_member' c.id %}" class="btn btn-edit"><i class="fas fa-edit"></i></a>
              <a href="{% url 'delete_member' c.id %}" class="btn btn-delete"
                ><i class="fas fa-trash-alt"></i
              ></a>
              {% endif %}
            </div>
          </div>
        </a>
      </div>
    </div>
    {% if forloop.counter|divisibleby:1 %}
    <div class="col-12 d-sm-none">
      <hr class="menus my-3" />
    </div>
    {% endif %} {% if forloop.counter|divisibleby:2 %}
    <div class="col-12 d-none d-sm-block d-md-none">
      <hr class="menus my-3" />
    </div>
    {% endif %} {% if forloop.counter|divisibleby:3 %}
    <div class="col-12 d-none d-md-block d-xl-none">
      <hr class="menus my-3" />
    </div>
    {% endif %} {% if forloop.counter|divisibleby:4 %}
    <div class="col-12 d-none d-xl-block">
      <hr class="menus my-3" />
    </div>
    {% endif %} {% endfor %}
  </div>
</div>
<div class="container my-5">
  <div class="row">
    <div class="col-12 text-center btt-btn">
      <a class="btt-link btn">
        <i class="fas fa-arrow-up"></i> Back to Top
        <i class="fas fa-arrow-up"></i>
      </a>
    </div>
  </div>
</div>
{% endblock %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %} {{ block.super }}
<script>
  $(".btt-link").click(function () {
    window.scrollTo(0, 0);
  });
</script>
{% endblock %}