Fantasy_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('console/', include('console.urls')),
    path('missions/', include('missions.urls')),
    path('news/', include('news.urls')),
    path('personnel/', include('personnel.urls')),
    path('profile/', include('user_profiles.urls')),
    path('resources/', include('resources.urls')),
    path('shopping-basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

missions/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.missions, name='missions'),
    path('<int:mission_id>/', views.mission_details, name='mission_details'),
    path('add-mission/', views.add_mission, name='add_mission'),
    path('pending-missions/', views.pending_missions, name='pending_missions'),
    path('edit-missions/<int:mission_id>/', views.edit_mission, name='edit_mission'),
    path('delete-mission/<int:mission_id>/', views.delete_mission, name='delete_mission'),
    path('<int:mission_id>/add-update/', views.add_update, name='add_update'),
    path('pending_updates/', views.pending_updates, name='pending_updates'),
    path('update-details/<int:update_id>/', views.update_details, name='update_details'),
    path('update-details/<int:update_id>/edit-update/', views.edit_update, name='edit_update'),
    path('delete-update/<int:update_id>/', views.delete_update, name='delete_update'),
]

missions/models.py
from django.db import models
from django.contrib.auth.models import User

from personnel.models import Personnel

# Create your models here.
GRADES = (
    (1, 'Extreme'),
    (2, 'Dangerous'),
    (3, 'Serious'),
    (4, 'Moderate'),
    (5, 'Basic'),
    (6, 'Training')
)

STATUS = (
    (1, 'Active'),
    (2, 'Completed'),
    (3, 'On Hold'),
    (4, 'Cancelled')
)

PUBLISH = ((0, 'Hidden'), (1, 'Displayed'))


class Mission(models.Model):
    """Set up our model for missions"""
    mission = models.CharField(
        max_length=100, null=False, blank=False, unique=True)
    mission_grade = models.IntegerField(choices=GRADES, default=5)
    mission_lead = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name="missions")
    description = models.TextField(max_length=2000, null=False, blank=False)
    prep_time = models.PositiveIntegerField(default=5)  # number in days
    mission_length = models.PositiveIntegerField(default=1)  # number in weeks
    mission_status = models.IntegerField(choices=STATUS, default=1)
    mission_img = models.ImageField(null=True, blank=True)
    img_url = models.URLField(max_length=1024, null=True, blank=True)
    approved_mission = models.IntegerField(choices=PUBLISH, default=0)

    class Meta:
        """Set up our extra model settings"""
        ordering = [
            'mission'
        ]

    def __str__(self):
        return self.mission

class Update(models.Model):
    """set up our new model for updates"""
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE, related_name='updates')
    title = models.CharField(max_length=100, default='')
    body = models.TextField(default='', max_length=2000)
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.PositiveIntegerField(choices=PUBLISH, default=0)

    class Meta:
        """set up class meta for Updates"""
        ordering = [
            'mission',
            'created_on'
        ]

    def __str__(self):
        return self.title

missions/forms.py
from django import forms
from django.forms import Select

from personnel.models import Personnel
from .models import Mission, Update

from .widgets import CustomClearableFileInput


class MissionForm(forms.ModelForm):
    """
    Form for creating a new mission to go 
    into our pending list
    """

    def __init__(self, *args, **kwargs):
        super(MissionForm, self).__init__(*args, **kwargs)
        self.fields['prep_time'].label = 'Preparation Time (in days)'
        self.fields['mission_length'].label = 'Mission Length (in weeks)'
        self.fields['approved_mission'].label = 'Approve Mission?'

    class Meta:
        """set up our form widgets"""
        model = Mission
        fields = [
            'mission',
            'mission_status',
            'mission_grade',
            'mission_lead',
            'prep_time',
            'mission_length',
            'mission_img',
            'img_url',
            'description',
            'approved_mission',
        ]
        widgets = {
            'mission': forms.TextInput(
                attrs={
                    'placeholder': 'Mission Title Here',
                }
            ),
            'mission_status': forms.Select(
                attrs={
                    'style': 'width: 200px;',
                }
            ),
            'mission_grade': forms.RadioSelect(),
            'img_url': forms.TextInput(
                attrs={'placeholder': 'Online Image URL'}
            ),
            'description': forms.Textarea(
                attrs={
                    'placeholder': 'Add Mission Description Here'
                }
            ),
            'prep_time': forms.NumberInput(
                attrs={
                    'style': 'width: 100px;',
                }
            ),
            'mission_length': forms.NumberInput(
                attrs={
                    'style': 'width: 100px;',
                }
            ),
            'approved_mission': forms.Select(
                attrs={
                    'style': 'width: 200px;',
                }
            )
        }

    mission_lead = forms.ModelChoiceField(
        queryset=Personnel.objects.filter(authorised=1)
    )
    mission_img = forms.ImageField(
        label='Image Upload',
        required=False,
        widget=CustomClearableFileInput,
    )


class ApproveMissionForm(forms.ModelForm):
    """Set up form for pending mission approval"""
    def __init__(self, *args, **kwargs):
        super(ApproveMissionForm, self).__init__(*args, **kwargs)
        self.fields['approved_mission'].label = 'How would you like to display this mission?'
    class Meta:
        """set up our form fields"""
        model = Mission
        fields = [
            'approved_mission'
        ]
        widgets = {
            'approved_mission': forms.Select(
                attrs={
                    'style': 'width: 100%;',
                }
            )
        }


class UpdateForm(forms.ModelForm):
    """Set up form for writing an update"""
    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = 'Update Contents'
    class Meta:
        """update meta for Update form"""
        model = Update
        fields = [
            'title',
            'body'
        ]
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'Update title here'
                }
            ),
            'body': forms.Textarea(
                attrs={
                    'placeholder': 'Add Update Contents Here'
                }
            ),
        }


class ApproveUpdateForm(forms.ModelForm):
    """set up a new form for approving updates"""
    def __init__(self, *args, **kwargs):
        super(ApproveUpdateForm, self).__init__(*args, **kwargs)
        self.fields['approved'].label = 'How would you like to display this update?'
    class Meta:
        """set up our form fields"""
        model = Update
        fields = [
            'approved'
        ]
        widgets = {
            'approved': forms.Select(
                attrs={
                    'style': 'width: 100%;',
                }
            )
        }

missions/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Mission, Update
from .forms import (
    MissionForm,
    ApproveMissionForm,
    UpdateForm,
    ApproveUpdateForm
)

# Create your views here.


def missions(request):
    """set up our standard missions page"""
    mission = Mission.objects.filter(approved_mission=1)

    context = {
        'mission': mission,
        'from_mission': True,
    }

    return render(request, 'missions/missions.html', context)


@login_required
def pending_missions(request):
    """set up our template for unapproved missions"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    mission = Mission.objects.filter(approved_mission=0)

    context = {
        'mission': mission,
        'from_homepage': True,
    }
    return render(request, 'missions/missions.html', context)


def mission_details(request, mission_id):
    """Set up how we display our mission brief"""
    from_pending = False
    mission = get_object_or_404(Mission, pk=mission_id)
    update = Update.objects.filter(approved=1)

    if mission.approved_mission == 0:
        from_pending = True

    if request.method == 'POST':
        form = ApproveMissionForm(
            request.POST,
            instance=mission
        )
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'You have successfully changed the approval of the mission!'
            )
            if mission.approved_mission == 0:
                from_pending = True
            else:
                from_pending = False
        else:
            messages.error(
                request,
                "You have failed to update this mission's approval"
            )
    else:
        form = ApproveMissionForm(instance=mission)

    context = {
        'mission': mission,
        'from_pending': from_pending,
        'form': form,
        'update': update,
    }

    return render(request, 'missions/mission-details.html', context)


@login_required
def add_mission(request):
    """set up our new view for adding a new mission"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = MissionForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'New Mission is awaiting review!'
            )
            return redirect(reverse('pending_missions'))
        else:
            messages.error(
                request,
                'Something went wrong - Please check through the form again!'
            )
    else:
        form = MissionForm()

    context = {
        'form': form,
    }
    return render(request, 'missions/add-mission.html', context)


@login_required
def edit_mission(request, mission_id):
    """Set up our page for editing missions"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    mission = get_object_or_404(Mission, pk=mission_id)
    if request.method == 'POST':
        form = MissionForm(
            request.POST,
            request.FILES,
            instance=mission
        )

        if form.is_valid():
            form.save()
            messages.success(
                request,
                f'Successfully update { mission.mission }!'
            )
            return redirect(reverse('missions'))
        else:
            messages.warning(request, (
                'Failed to update Mission'
                'Please check through the form again!'
            ))
    else:
        form = MissionForm(instance=mission)
        messages.info(
            request,
            f'You are editing { mission.mission }'
        )

    context = {
        'mission': mission,
        'form': form,
    }
    return render(request, 'missions/edit-mission.html', context)


@login_required
def delete_mission(request, mission_id):
    """set up our view to delete missions"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    mission = get_object_or_404(Mission, pk=mission_id)
    if request.method == 'POST':
        mission.delete()
        messages.success(
            request,
            f'You have successfully deleted { mission.mission }'
        )
        return redirect(reverse('missions'))

    context = {
        'mission': mission,
    }
    return render(request, 'missions/delete-mission.html', context)


@login_required
def add_update(request, mission_id):
    """set up a view for adding an update"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    mission = get_object_or_404(Mission, pk=mission_id)
    if request.method == 'POST':
        form = UpdateForm(
            request.POST
        )
        if form.is_valid():
            form.instance.mission = mission
            form.save()
            messages.success(
                request,
                f'You have added an Update to { mission.mission }'
            )
            return redirect(reverse('missions'))
    else:
        form = UpdateForm()

    context = {
        'mission': mission,
        'form': form,
    }

    return render(request, 'missions/add_update.html', context)


@login_required
def pending_updates(request):
    """set up a view for all the updates"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    updates = Update.objects.filter(approved=0)

    context = {
        'updates': updates,
    }

    return render(request, 'missions/pending-updates.html', context)

@login_required
def update_details(request, update_id):
    """set up the view to fully display an update"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    update = get_object_or_404(Update, pk=update_id)

    if request.method == 'POST':
        form = ApproveUpdateForm(
            request.POST,
            instance=update
        )
        if form.is_valid():
            form.save()
            messages.success(
                request,
                'You have successfully changed the approval of the update!'
            )
        else:
            messages.error(
                request,
                "You have failed to approve this Update!"
            )
    else:
        form = ApproveUpdateForm(instance=update)

    context = {
        'update': update,
        'form': form,
    }

    return render(request, 'missions/update-details.html', context)

@login_required
def edit_update(request, update_id):
    """Set up our page for editing missions"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    update = get_object_or_404(Update, pk=update_id)

    if request.method == 'POST':
        form = UpdateForm(
            request.POST,
            instance=update
        )

        if form.is_valid():
            form.save()
            messages.success(
                request,
                f'Successfully update { update.title }!'
            )
            return redirect('update_details', update_id)
        else:
            messages.error(request, (
                'Failed to edit Update'
                'Please check through the form again!'
            ))
    else:
        form = UpdateForm(instance=update)
        messages.info(
            request,
            f'You are editing { update.title }'
        )

    context = {
        'update': update,
        'form': form,
    }
    return render(request, 'missions/edit-update.html', context)

@login_required
def delete_update(request, update_id):
    """set up our view to delete missions"""
    if not request.user.is_superuser:
        messages.error(
            request,
            'You are not authorised to access this Resource!'
        )
        return redirect(reverse('home'))

    update = get_object_or_404(Update, pk=update_id)
    if request.method == 'POST':
        update.delete()
        messages.success(
            request,
            f'You have successfully deleted { update.title }'
        )
        return redirect(reverse('missions'))

    context = {
        'update': update,
    }
    return render(request, 'missions/delete-update.html', context)

missions/templates/missions/delete-mission.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Delete Mission{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container">
    <div class="row text-center">
        <div class="col-12 text-center">
            <h3 class="renegade page-heading">Delete Mission</h3>
            <p class="league page-subhead">
                Are you sure you want to delete the following Mission?</em>
            </p>
        </div>
        <hr class="menus">
        <div class="col-12">
            <p class="league page-subhead">{{ mission.mission|upper }}</p>
            <p class="league page-subhead">{{ mission.get_mission_grade_display }} - {{ mission.get_mission_status_display }}</p>
        </div>
        <div class="col-12 menus page-heading my-5">
            <h1>WARNING - Deleting this mission will remove it from the console permanently!</h1>
        </div>
        <div class="my-3">
            <form method="post" class="form">
                {% csrf_token %}
                <a href="{% url 'missions' %}" class="btn-lg btn-console-link"><i class="fas fa-chevron-circle-left"></i> Cancel</a>
                <button class="btn-lg btn-console-link" type="submit">X Delete</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

missions/templates/missions/mission-details.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- add extra css stylesheet -->
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/mission-details.css' %}" />
{% endblock %}

<!-- set up tab extra title -->
{% block extra_title %} - Mission Brief{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container text-center">
    <div class="row">
        <div class="col-12 text-center">
            <h3 class="renegade page-heading">Latest Mission Report</h3>
            <p class="league page-subhead">
                This is the latest information we have received from the team leader regarding the mission.</em>
            </p>
        </div>
        <div class="col-12 content-titles">
            {% if from_pending == True %}
            <a href="{% url 'pending_missions' %}" class="menus">
                <i class="fas fa-chevron-circle-left"></i> Pending Missions
            </a>
            {% else %}
            <a href="{% url 'missions' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Missions</a>
            {% endif %}
            <a href="{% url 'console' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Console</a>
        </div>
    </div>
</div>
<hr class="menus" />
{% if request.user.is_superuser %}
<div class="container">
    <div class="row mb-5">
        <div class="col-12 text-center">
            <a href="{% url 'edit_mission' mission.id %}" class="btn-console-link">
                <span class="my-3">Edit Mission</span>
            </a>
            <a href="{% url 'delete_mission' mission.id %}" class="btn-console-link">
                <span class="my-3">Delete Mission</span>
            </a>
        </div>
    </div>
</div>
{% endif %}
<div class="container current-mission">
    <div class="row">
        <div class="col-12">
            <h3 class="league mb-3 mx-4">Current Mission Status -
                <span
                    class="status-blink {% if mission.mission_status == 1 %}league{% elif mission.mission_status == 2 %}renegade{% else %}menus{% endif %}">
                    {{ mission.get_mission_status_display|upper }}
                </span>
            </h3>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 text-center">
            {% if mission.mission_image %}
            <img class="mission-img mb-3" src="{{ mission.mission_img.url }}" alt="{{ mission.mission }} profile image" />
            {% else %}
            <img class="mission-img mb-3" src="{{ MEDIA_URL }}mission-default-image.png" alt="No image available" />
            {% endif %}
        </div>
        <div class="col-12 col-md-6 league mission-breakdown">
            <p>Mission Title: <strong>{{ mission.mission }}</strong></p>
            <p>Mission being led by: <strong>{{ mission.mission_lead }}</strong></p>
            <p>Prep Time: <strong>{{ mission.prep_time }} days</strong></p>
            <p>Estimated mission length: <strong>{{ mission.mission_length }} weeks</strong></p>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-10 offset-1 league mission-desc">
            <p><strong>Mission Description:</strong></p>
            <p>{{ mission.description|linebreaks }}</p>
        </div>
    </div>
</div>
{% if request.user.is_superuser %}
<hr class="menus">
<div class="container text-center league">
    <div class="row">
        <div class="col-12">
            <p class="page-subhead">This brief is currently {{ mission.get_approved_mission_display|lower }} to the general users</p>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-8 offset-2 col-md-4 offset-md-4 form-inner-content">
            <form action="{% url 'mission_details' mission.id %}" method="POST" class="form mt-3 mb-2 card-origins approval-form">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn-console-link mt-3" type="submit">Update Approval</button>
            </form>
        </div>
    </div>
</div>
{% endif %}
<hr class="menus">
<!-- This is the updates section for our mission -->
<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h3 class="page-heading renegade text-center mb-5">Mission Updates</h3>
            {% if not mission.updates.all %}
            <p class="page-subhead league">
                There are currently no updates for this Mission
            </p>
            {% endif %}
        </div>
    </div>
    {% for u in mission.updates.all %}
        {% if u.approved == 1 %}
        <div class="row">
            <div class="col-10 offset-1">
                <a href="{% url 'update_details' u.id %}" class="menus plain-link">
                <p><strong>{{ mission.mission_lead }} - {{ u.created_on }}</strong></p>
                <p><strong>{{ u.title }}</strong></p>
                </a>
            </div>
            <div class="col-10 offset-1 league mission-desc">
                <p>{{ u.body }}</p>
            </div>
        </div>
        <hr class="menus">
        {% else %}
        {% if request.user.is_superuser %}
        <div class="row">
            <div class="col-10 offset-1 my-3">
                <a href="{% url 'update_details' u.id %}" class="menus plain-link">
                    You have a pending update that needs approval
                </a>
            </div>
        </div>
        <hr class="menus">
        {% endif %}
        {% endif %}
    {% endfor %}
    {% if request.user.is_superuser %}
    <div class="row">
        <div class="col-12 text-center my-5">
            <a href="{% url 'add_update' mission.id %}" class="btn-console-link">Write an update now</a>
        </div>
    </div>
    {% endif %}
</div>


<hr class="menus">

<!-- back to top button -->
<div class="container">
    <div class="row">
        <div class="col-12 text-center btt-btn">
            <a class="btt-link btn">
                <i class="fas fa-arrow-up"></i> Back to Top
                <i class="fas fa-arrow-up"></i>
            </a>
        </div>
    </div>
</div>
{% endblock content %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %} {{ block.super }}
<script>
    $(".btt-link").click(function () {
        window.scrollTo(0, 0);
    });
</script>
{% endblock %}

missions/templates/missions/missions.html
{% extends 'base.html' %}

<!-- set  up load static -->
{% load static %}

<!-- set up tab extra title -->
{% block extra_title %} - Mission Log{% endblock %}

<!-- set up page header to push ccon down -->
{% block page_header %}
<div class="container header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock%}

<!-- set up main content block -->
{% block content %}
<div class="cover-up"></div>
<div class="container text-center">
  <div class="row">
    <div class="col-12 text-center">
      <h3 class="renegade page-heading">Mission Briefs</h3>
      <p class="league page-subhead">
        {% if from_homepage %}
        These are the Unapproved Missions awaiting your review
        {% else %}
        Here are all the missions the team are currently completing or have
        completed.
        {% endif %}
      </p>
    </div>
    <div class="col-12 content-titles">
      {% if from_homepage %}
      <a href="{% url 'home' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Home</a>
      {% endif %}
      <a href="{% url 'console' %}" class="menus btn"><i class="fas fa-chevron-circle-left"></i> Console</a>
    </div>
  </div>
</div>
<hr class="menus" />
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center content-titles">
      {% if from_homepage and request.user.is_superuser %}
      <a href="{% url 'missions' %}"><i class="fas fa-chevron-circle-left"></i> Approved Missions</a>
      {% elif request.user.is_superuser %}
      <a href="{% url 'pending_missions' %}"><i class="fas fa-chevron-circle-left"></i> Pending Missions</a>
      {% endif %}
    </div>
  </div>
  <div class="row my-5">
  {% if mission|length == 0 %}
    <div class="col-12 text-center league">
      <h5>There are no news articles to display!</h5>
    </div>
  {% endif %}
  </div>
  <div class="row mb-3">
    {% for m in mission %}
    <div class="col-sm-6 col-md-4 col-xl-3 mb-5">
      <div class="card mission-card">
        <div class="row">
          <div class="col">
            <a href="{% url 'mission_details' m.id %}">
              <div class="card-img-holder">
                {% if m.mission_image %}
                <img
                  class="card-img-top"
                  src="{{ m.mission_img.url }}"
                  alt="{{ m.mission }} profile image"
                />
                {% else %}
                <img
                  class="card-img-top"
                  src="{{ MEDIA_URL }}mission-default-image.png"
                  alt="No image available"
                />
                {% endif %}
              </div>
            </a>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <a href="{% url 'mission_details' m.id %}">
              <div class="card-body text-center void">
                <h5 class="card-title">{{ m.mission|upper }}</h5>
                <p class="card-origins">
                  Grade -
                  <strong>{{ m.get_mission_grade_display }}</strong>
                  | Status - <strong>{{ m.get_mission_status_display }}</strong>
                </p>
                <p class="card-text">
                  <em> Lead - <strong>{{ m.mission_lead|upper }}</strong></em>
                </p>
              </div>
            </a>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <a href="{% url 'mission_details' m.id %}" class="btn btn-view"
              ><span class="d-none d-lg-inline-block">View </span>
              <i class="fas fa-eye"></i
            ></a>
            {% if request.user.is_superuser %}
            <a href="{% url 'edit_mission' m.id %}" class="btn btn-edit"><i class="fas fa-edit"></i></a>
            <a href="{% url 'delete_mission' m.id %}" class="btn btn-delete"
              ><i class="fas fa-trash-alt"></i
            ></a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:1 %}
    <div class="col-12 d-sm-none">
      <hr class="menus" />
    </div>
    {% endif %} {% if forloop.counter|divisibleby:2 %}
    <div class="col-12 d-none d-sm-block d-md-none">
      <hr class="menus my-3" />
    </div>
    {% endif %} {% if forloop.counter|divisibleby:3 %}
    <div class="col-12 d-none d-md-block d-xl-none">
      <hr class="menus my-3" />
    </div>
    {% endif %} {% if forloop.counter|divisibleby:4 %}
    <div class="col-12 d-none d-xl-block">
      <hr class="menus my-3" />
    </div>
    {% endif %} {% endfor %}
  </div>
</div>
<div class="container my-5">
  <div class="row">
    <div class="col-12 text-center btt-btn">
      <a class="btt-link btn">
        <i class="fas fa-arrow-up"></i> Back to Top
        <i class="fas fa-arrow-up"></i>
      </a>
    </div>
  </div>
</div>
<!-- set up footer for page -->
{% endblock content %}

{% block page_footer %}
<div class="container footer-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block postloadjs %} {{ block.super }}
<script>
  $(".btt-link").click(function () {
    window.scrollTo(0, 0);
  });
</script>
{% endblock %}